apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: DevOpsProject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: api
        image:  essole/linkextractor-api:v1-py
        ports:
        - containerPort: 5000
      - name: web
        image:  essole/linkextractor-web:v1-php
        ports:
        - containerPort: 8081
      - name: redis
        image:  redis
        
      


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: DevOpsProject
spec:
  selector:
    app: web
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  -port: 8081
    protocol: TCP
    targetPort: 80
  
